#pragma once

#define DEFAULT_BAUDRATE 115200

#define INGCHIPS_KEYBOARD_VID 0xFFF1
#define INGCHIPS_KEYBOARD_PID 0xFA2F
#define INGCHIPS_KEYBOARD_IINTERFACE 0
#define INGCHIPS_KEYBOARD_EP_OUT 0x02
#define INGCHIPS_KEYBOARD_EP_IN 0x81
#define DEFAULT_WRITE_TIMEOUT 1000